# Table of Contents
1. [Consulta de dados de alertas para a cidade do Rio de Janeiro](#Consulta-de-dados-de-alertas-para-a-cidade-do-Rio-de-Janeiro)
   - [Consulta em formato JSON](#Consulta-em-formato-JSON)
   - [Fazendo download em formato CSV](#Fazendo-download-em-formato-CSV)
   - [Tratamento de Erros](#Tratamento-de-Erros)
2. [Extraindo dados com PySUS (Python)](#Extraindo-dados-com-PySUS-(Python))

In [1]:
import pandas as pd

# AlertaDengue API

A API AlertaDengue foi desenhada para atender às Secretarias de Saúde que necessitam dos dados do sistema para a integração em suas próprias rotinas.

A API disponibiliza a seguinte funcionalidade:

* consulta de dados de alertas para a cidade do Rio de Janeiro.

## Consulta de dados de alertas para a cidade do Rio de Janeiro

Esssa funcionalidade está disponível por meio da URL:

```
https://info.dengue.mat.br/api/alertcity?<PARAMETROS_DA_CONSULTA>
```

Onde `<PARAMETROS_DA_CONSULTA>` deve conter os parâmetros:

* geocode: código IBGE da cidade
* disease: tipo de doença a ser consultado (str:dengue|chikungunya|zika)
* format: formato de saída dos dados (str:json|csv)
* ew_start: semana epidemiológica de início da consulta (int:1-53)
* ew_end: semana epidemiológica de final da consulta (int:1-53)
* e_year: ano de referência da consulta (int:0-9999)

Todos os parâmetros acima mencionados são obrigatórios para a consulta.

Abaixo, segue exemplo de requisição de registros de dengue entre a 
semana 1 e 50 do ano de 2017, em formato `CSV`:

```
https://info.dengue.mat.br/api/alertcity?geocode=3304557&disease=dengue&format=csv&ew_start=1&ew_end=50&e_year=2017
```

A continuação, seguem exemplos de uso da API referente a funcionalidade descrita.

### Consulta em formato JSON

In [22]:
# 3304557 = Rio de Janeiro city geocode
url = 'https://info.dengue.mat.br/api/alertcity'
search_filter = (
    'geocode=3304557&disease=dengue&format=json&' +
    'ew_start=1&ew_end=50&ey_start=2017&ey_end=2017'
)
df = pd.read_json('%s?%s' % (url, search_filter))
df.head()

,data_iniSE,SE,casos_est,casos_est_min,casos_est_max,casos,p_rt1,p_inc100k,Localidade_id,nivel,...,umidmed,umidmin,tempmed,tempmax,casprov,casprov_est,casprov_est_min,casprov_est_max,casconf,notif_accum_year
0,1512864000000,201750,71,71,71,71,0.757232,1.052192,0,2,...,77.255571,69.549886,23.623814,24.857143,NaN,NaN,NaN,NaN,NaN,4596
1,1512259200000,201749,81,81,81,81,0.984041,1.200389,0,2,...,76.802857,69.908857,24.258000,25.857143,NaN,NaN,NaN,NaN,NaN,4596
2,1511654400000,201748,60,60,60,60,0.687503,0.889177,0,2,...,72.243743,59.833229,25.166657,27.428571,NaN,NaN,NaN,NaN,NaN,4596
3,1511049600000,201747,51,51,51,51,0.400404,0.755800,0,2,...,77.717186,58.370186,24.523800,28.142857,NaN,NaN,NaN,NaN,NaN,4596
4,1510444800000,201746,55,55,55,55,0.684003,0.815079,0,2,...,54.200400,33.575350,28.951100,34.500000,NaN,NaN,NaN,NaN,NaN,4596

In [26]:
# 4106902 = Curitiba city geocode
url = 'https://info.dengue.mat.br/api/alertcity'
search_filter = (
    'geocode=4106902&disease=dengue&format=json&' +
    'ew_start=1&ew_end=50&ey_start=2017&ey_end=2017'
)
df = pd.read_json('%s?%s' % (url, search_filter))
df.head()

,data_iniSE,SE,casos_est,casos_est_min,casos_est_max,casos,p_rt1,p_inc100k,Localidade_id,nivel,...,umidmed,umidmin,tempmed,tempmax,casprov,casprov_est,casprov_est_min,casprov_est_max,casconf,notif_accum_year
0,1512864000000,201750,36,36,36,36,0.814476,1.847456,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1944
1,1512259200000,201749,33,33,33,33,0.703381,1.693501,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1944
2,1511654400000,201748,25,25,25,25,0.343987,1.282955,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1944
3,1511049600000,201747,29,29,29,29,0.807684,1.488228,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1944
4,1510444800000,201746,34,34,34,34,0.984994,1.744819,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1944

### Fazendo download em formato CSV

In [27]:
import urllib.request
urllib.request.urlretrieve(
    'https://info.dengue.mat.br/api/alertcity?'
    'geocode=4106902&disease=dengue&format=json'
    '&ew_start=1&ew_end=50&ey_start=2017&ey_end=2017', 
    'cwb_dengue.csv'
)

('cwb_dengue.csv', <http.client.HTTPMessage at 0x7fcfc5254580>)

### Tratamento de Erros

In [ ]:
params = [
    '',
    'disease=dengue',
    'geocode=3304557',
    'format=csv',
    'ew_start=1',
    'ew_end=50',
    'e_year=2017'
]

search_filter = ''
sep = ''
for param in params:
    print('-' * 80)
    
    search_filter += sep + param
    url_search = '%s?%s' % (url, search_filter)
    
    print(url_search)
    
    df = pd.read_csv(url_search)
    sep = '&'
    print(df.head())

--------------------------------------------------------------------------------
http://localhost:8000/api/alertcity?
Empty DataFrame
Columns: [[EE] error_message: Disease sent is empty.]
Index: []
--------------------------------------------------------------------------------
http://localhost:8000/api/alertcity?&disease=dengue
Empty DataFrame
Columns: [[EE] error_message: GEO-Code sent is empty.]
Index: []
--------------------------------------------------------------------------------
http://localhost:8000/api/alertcity?&disease=dengue&geocode=3304557
Empty DataFrame
Columns: [[EE] error_message: Format sent is empty.]
Index: []
--------------------------------------------------------------------------------
http://localhost:8000/api/alertcity?&disease=dengue&geocode=3304557&format=csv
Empty DataFrame
Columns: [[EE] error_message: Epidemic start week sent is empty.]
Index: []
--------------------------------------------------------------------------------
http://localhost:8000/api/alertcity?&disease=dengue&geocode=3304557&format=csv&ew_start=1
Empty DataFrame
Columns: [[EE] error_message: Epidemic end week sent is empty.]
Index: []
--------------------------------------------------------------------------------
http://localhost:8000/api/alertcity?&disease=dengue&geocode=3304557&format=csv&ew_start=1&ew_end=50
Empty DataFrame
Columns: [[EE] error_message: Epidemic year sent is empty.]
Index: []
--------------------------------------------------------------------------------
http://localhost:8000/api/alertcity?&disease=dengue&geocode=3304557&format=csv&ew_start=1&ew_end=50&e_year=2017
       id  aps      se        data  casos  casos_est  casos_estmin  \
0  190034  2.1  201724  2017-06-11      1        1.0           1.0
1  213390  2.1  201733  2017-08-13      5        5.0           5.0
2  217372  2.1  201734  2017-08-20      2        2.0           2.0
3  225358  2.1  201737  2017-09-10      3        3.0           3.0
4  229380  2.1  201738  2017-09-17      4        4.0           4.0

   casos_estmax     tmin        rt      prt1       inc  nivel
0           1.0  18.8571  0.349526  0.137641  0.180933      1
1           5.0  19.7143  1.777530  0.797493  0.904665      1
2           2.0  18.2857  0.664763  0.311178  0.361866      1
3           3.0  17.9714  1.266840  0.616171  0.542799      1
4           4.0  18.3429  1.820440  0.783039  0.723732      1

## Extraindo dados com PySUS (Python)

[PySUS](https://github.com/AlertaDengue/PySUS) é um pacote Python para extrair dados da saúde. Com esta ferramenta, é possível fazer o download das semanas epidemiológicas com scripts em Python. Tutoriais sobre a utilização do PySUS para extração dos dados no sistema InfoDengue pode ser encontrada na [documentação oficial do PySUS](https://pysus.readthedocs.io/en/latest/Infodengue.html)